name: isolate_executor
description: This library contains types that allow for executing code in a spawned isolate, perhaps with additional imports.
version: 2.0.0-dev.2
homepage: https://github.com/stablekernel/dart-isolate-executor
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.0.0-dev <3.0.0"

dependencies:
  analyzer: '>=0.32.0 <0.33.0'

dev_dependencies:
  test: ^1.0.0
  test_package:
    path: test/test_package
