name: conduit_isolate_exec
description: This library contains types that allow for executing code in a spawned isolate, perhaps with additional imports.
version: 1.0.0-b1
homepage: https://github.com/stablekernel/dart-isolate-executor
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  analyzer: ^1.3.0
  glob: ^2.0.0

dev_dependencies:
  lint: ^1.5.3
  test: ^1.6.5
  test_package:
    path: test/test_package
